import { defineMeta } from "blume";

export default defineMeta({
  title: "OpenPets",
  pages: [
    "index",
    "quickstart",
    "install",
    "desktop",
    "pets",
    "agent-integrations",
    "official-plugins",
    "plugins",
    "sdk",
    "i18n",
    "cli",
    "mcp",
    "ipc",
    "pet-format",
    "catalog",
    "troubleshooting",
    "lan-mode",
    "wayland",
    "wayland-layer-shell",
    "architecture",
    "development",
    "testing-and-validation",
    "release",
  ],
});
